[workspace]
authors = ["Elian NEPPEL <elian.dev@posteo.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "afor"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.10,<3.15"

[tasks]
test = "python3 -m pytest ./tests"

[environments]
default = { features = ["jazzy", "dev", "zenoh"] }
humble = { features = ["humble", "dev", "zenoh"] }
jazzy = { features = ["jazzy", "dev", "zenoh"] }
kilted = { features = ["kilted", "dev", "zenoh"] }
lyrical = { features = ["lyrical", "dev", "zenoh"] }
py310 = {features = ["zenoh", "dev", "py310"]}
py311 = {features = ["zenoh", "dev", "py311"]}
py312 = {features = ["zenoh", "dev", "py312"]}
py313 = {features = ["zenoh", "dev", "py313"]}
py314 = {features = ["zenoh", "dev", "py314"]}
zenoh = { features = ["zenoh", "dev"] }
dds = { features = ["dds", "dev"] }
dev = { features = ["dev"] }

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.zenoh.dependencies]
zenoh = "*"

[feature.zenoh.pypi-dependencies]
eclipse-zenoh = "*"

[feature.dds.dependencies]
python = ">=3.10,<3.14"

[feature.dds.pypi-dependencies]
cyclonedds = ">=11"

[feature.dev.dependencies]
colorama = "*"
pytest = "*"
pytest-asyncio = "*"

[feature.dev.pypi-dependencies]
asyncio_for_robotics = { path = ".", editable=true}


### ROS Humble ####
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-ros-core = "*"
ros-humble-demo-nodes-py = "*"
ros-humble-rmw-fastrtps-cpp = "*"

[feature.humble.activation.env]
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

### ROS Jazzy ####
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros-core = "*"
ros-jazzy-demo-nodes-py = "*"
ros-jazzy-rmw-fastrtps-cpp = "*"

[feature.jazzy.activation.env]
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

### ROS Kilted ####
[feature.kilted]
channels = ["https://prefix.dev/robostack-kilted"]

[feature.kilted.dependencies]
ros-kilted-ros-core = "*"
ros-kilted-demo-nodes-py = "*"
ros-kilted-rmw-fastrtps-cpp = "*"

[feature.kilted.activation.env]
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

### ROS Lyrical ####
[feature.lyrical]
channels = ["https://prefix.dev/robostack-lyrical"]

[feature.lyrical.dependencies]
ros-lyrical-ros-core = "*"
ros-lyrical-demo-nodes-py = "*"
ros-lyrical-rmw-fastrtps-cpp = "*"

[feature.lyrical.activation.env]
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

[package] 
name = "asyncio_for_robotics"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }

# [package.run-dependencies]
# asyncio_for_robotics = { path = "."}
